Repository genn-team/genn, pull requests merged in 2020-07, with the labels that each got.

#341 Windows SpineML fixes
  include/genn/third_party/plog/Appenders/EventLogAppender.h
  include/genn/third_party/plog/Appenders/RollingFileAppender.h
  include/genn/third_party/plog/Converters/NativeEOLConverter.h
  include/genn/third_party/plog/Init.h
  include/genn/third_party/plog/Log.h
  include/genn/third_party/plog/Logger.h
  include/genn/third_party/plog/Record.h
  include/genn/third_party/plog/Severity.h
  include/genn/third_party/plog/Util.h
  include/genn/third_party/plog/WinApi.h
  src/spineml/common/spineml_common.vcxproj
  src/spineml/simulator/spineml_simulator.vcxproj
  src/spineml/standalone_simulator/spineml_standalone_simulator.vcxproj
Labels: SpineML, bug

#338 Host connectivity init fixes when used with CPU backend
  src/genn/backends/single_threaded_cpu/backend.cc
  src/genn/genn/code_generator/groupMerged.cc
  tests/features/connect_init/Makefile
  tests/features/connect_init/connect_init.sln
  tests/features/connect_init/connect_init.vcxproj
  tests/features/connect_init/model.cc
  tests/features/connect_init/runner_guid.txt
  tests/features/connect_init/test.cc
Labels: bug

#339 get connectivity from device for on-device init
  include/genn/genn/initSparseConnectivitySnippet.h
  pygenn/genn_groups.py
Labels: PyGeNN, bug

#344 Device only connectivity fix
  pygenn/genn_groups.py
Labels: PyGeNN, bug

#348 Correctly simulate models with very small timesteps
  src/genn/genn/code_generator/generateRunner.cc
Labels: bug

#350 Fix bug in merging logic for detecting which parameters are 'heterogeneus'
  include/genn/genn/code_generator/groupMerged.h
  src/genn/genn/code_generator/groupMerged.cc
  tests/unit/neuronGroup.cc
  tests/unit/synapseGroup.cc
Labels: bug

#349 Fix for bug in logic for merging synapse groups with procedural variables
  src/genn/genn/synapseGroup.cc
  tests/unit/synapseGroup.cc
Labels: bug
