Repository genn-team/genn, pull requests merged in 2020-04, with the labels that each got.

#312 small fix
  src/genn/genn/code_generator/generateNeuronUpdate.cc
Labels: bug

#315 renormalize line endings
  include/genn/third_party/plog/Appenders/AndroidAppender.h
  include/genn/third_party/plog/Appenders/ColorConsoleAppender.h
  include/genn/third_party/plog/Appenders/ConsoleAppender.h
  include/genn/third_party/plog/Appenders/IAppender.h
  include/genn/third_party/plog/Appenders/RollingFileAppender.h
  include/genn/third_party/plog/Converters/UTF8Converter.h
  include/genn/third_party/plog/Formatters/CsvFormatter.h
  include/genn/third_party/plog/Formatters/FuncMessageFormatter.h
  include/genn/third_party/plog/Formatters/TxtFormatter.h
  include/genn/third_party/plog/Init.h
  include/genn/third_party/plog/Log.h
  include/genn/third_party/plog/Logger.h
  include/genn/third_party/plog/Record.h
  include/genn/third_party/plog/Severity.h
  include/genn/third_party/plog/Util.h
  userproject/HHVclampGA_project/README.txt
  userproject/Izh_sparse_project/README.txt
  userproject/MBody1_project/README.txt
  userproject/OneComp_project/README.txt
  userproject/PoissonIzh_project/README.txt
  userproject/SynDelay_project/README.txt
Labels: bug

#317 Fix for nasty bug in single-threaded CPU backend
  src/genn/backends/single_threaded_cpu/backend.cc
Labels: bug

#318 Windows fixes
  bin/genn-buildmodel.bat
  src/genn/generator/generator.vcxproj
Labels: bug, enhancement

#316 Completion of merging implementation
  include/genn/backends/cuda/backend.h
  include/genn/backends/cuda/presynapticUpdateStrategy.h
  include/genn/backends/single_threaded_cpu/backend.h
  include/genn/genn/code_generator/backendBase.h
  include/genn/genn/code_generator/codeGenUtils.h
  include/genn/genn/code_generator/generateInit.h
  include/genn/genn/code_generator/generateNeuronUpdate.h
  include/genn/genn/code_generator/generateRunner.h
  include/genn/genn/code_generator/generateSynapseUpdate.h
  include/genn/genn/code_generator/groupMerged.h
  include/genn/genn/code_generator/mergedStructGenerator.h
  include/genn/genn/code_generator/modelSpecMerged.h
  include/genn/genn/code_generator/substitutions.h
  include/genn/genn/gennUtils.h
  include/genn/genn/initSparseConnectivitySnippet.h
  include/genn/genn/models.h
  include/genn/genn/snippet.h
  include/genn/genn/synapseGroup.h
  include/genn/genn/synapseGroupInternal.h
  pygenn/README.md
  pygenn/genn_model.py
  src/genn/backends/cuda/backend.cc
  src/genn/backends/cuda/optimiser.cc
  src/genn/backends/cuda/presynapticUpdateStrategy.cc
  src/genn/backends/single_threaded_cpu/backend.cc
  src/genn/genn/code_generator/codeGenUtils.cc
  src/genn/genn/code_generator/generateAll.cc
  src/genn/genn/code_generator/generateInit.cc
  src/genn/genn/code_generator/generateNeuronUpdate.cc
  src/genn/genn/code_generator/generateRunner.cc
  src/genn/genn/code_generator/generateSynapseUpdate.cc
  src/genn/genn/code_generator/groupMerged.cc
  src/genn/genn/code_generator/modelSpecMerged.cc
  src/genn/genn/code_generator/substitutions.cc
  src/genn/genn/currentSource.cc
  src/genn/genn/genn.vcxproj
  src/genn/genn/gennUtils.cc
  src/genn/genn/initSparseConnectivitySnippet.cc
  src/genn/genn/modelSpec.cc
  src/genn/genn/neuronGroup.cc
  src/genn/genn/synapseGroup.cc
  tests/features/current_source_rng_normal/current_source_rng_normal.vcxproj
  tests/run_tests.bat
  tests/run_tests.sh
  tests/unit/Makefile
  tests/unit/currentSource.cc
  tests/unit/initSparseConnectivitySnippet.cc
  tests/unit/initVarSnippet.cc
  tests/unit/neuronGroup.cc
  tests/unit/synapseGroup.cc
  tests/unit/unit.vcxproj
  userproject/PotjansMicrocircuit_project/model/PotjansMicrocircuitSim.cc
  userproject/include/fixedNumberTotalPreCalc.h
Labels: enhancement

#319 Add push/pull_extra_global_param function to pygenn/genn_models.py.
  pygenn/genn_model.py
Labels: enhancement

#321 Fix compilation with gcc 4.9
  userproject/include/spikeRecorder.h
Labels: bug, userprojects
