Repository genn-team/genn, pull requests merged in 2020-10, with the labels that each got.

#373 Kernel-based connectivity
  generate_swig_interfaces.py
  include/genn/backends/cuda/backend.h
  include/genn/backends/opencl/backend.h
  include/genn/backends/single_threaded_cpu/backend.h
  include/genn/genn/code_generator/backendBase.h
  include/genn/genn/code_generator/backendSIMT.h
  include/genn/genn/code_generator/codeGenUtils.h
  include/genn/genn/code_generator/groupMerged.h
  include/genn/genn/initSparseConnectivitySnippet.h
  include/genn/genn/initVarSnippet.h
  include/genn/genn/postsynapticModels.h
  include/genn/genn/synapseGroup.h
  pygenn/genn_model.py
  src/genn/backends/cuda/backend.cc
  src/genn/backends/opencl/backend.cc
  src/genn/backends/single_threaded_cpu/backend.cc
  src/genn/genn/code_generator/backendSIMT.cc
  src/genn/genn/code_generator/generateInit.cc
  src/genn/genn/code_generator/generateSynapseUpdate.cc
  src/genn/genn/code_generator/groupMerged.cc
  src/genn/genn/code_generator/presynapticUpdateStrategySIMT.cc
  src/genn/genn/initSparseConnectivitySnippet.cc
  src/genn/genn/initVarSnippet.cc
  src/genn/genn/synapseGroup.cc
  tests/features/constant_cache_overflow/skip_OpenCL
  tests/features/decode_matrix_conn_gen_individualg_ragged_kernel/Makefile
  tests/features/decode_matrix_conn_gen_individualg_ragged_kernel/decode_matrix_conn_gen_individualg_ragged_kernel.sln
  tests/features/decode_matrix_conn_gen_individualg_ragged_kernel/decode_matrix_conn_gen_individualg_ragged_kernel.vcxproj
  tests/features/decode_matrix_conn_gen_individualg_ragged_kernel/model.cc
  tests/features/decode_matrix_conn_gen_individualg_ragged_kernel/runner_guid.txt
  tests/features/decode_matrix_conn_gen_individualg_ragged_kernel/test.cc
  tests/features/decode_matrix_conn_gen_proceduralg_procedural_kernel/Makefile
  tests/features/decode_matrix_conn_gen_proceduralg_procedural_kernel/decode_matrix_conn_gen_proceduralg_procedural_kernel.sln
  tests/features/decode_matrix_conn_gen_proceduralg_procedural_kernel/decode_matrix_conn_gen_proceduralg_procedural_kernel.vcxproj
  tests/features/decode_matrix_conn_gen_proceduralg_procedural_kernel/model.cc
  tests/features/decode_matrix_conn_gen_proceduralg_procedural_kernel/runner_guid.txt
  tests/features/decode_matrix_conn_gen_proceduralg_procedural_kernel/skip_SingleThreadedCPU
  tests/features/decode_matrix_conn_gen_proceduralg_procedural_kernel/test.cc
  tests/utils/conv_data.h
  tests/utils/simulation_test.h
Labels: bug, enhancement

#361 Fix for old CUDA versions and impove warning suppression
  src/genn/backends/cuda/backend.cc
Labels: bug, enhancement

#372 Efficient spike/spike-like event recording
  doxygen/13_UserGuide.dox
  generate_swig_interfaces.py
  include/genn/backends/opencl/backend.h
  include/genn/backends/single_threaded_cpu/backend.h
  include/genn/genn/code_generator/backendBase.h
  include/genn/genn/code_generator/backendSIMT.h
  include/genn/genn/code_generator/modelSpecMerged.h
  include/genn/genn/modelSpec.h
  include/genn/genn/modelSpecInternal.h
  include/genn/genn/neuronGroup.h
  pygenn/genn_groups.py
  pygenn/genn_model.py
  setup.py
  src/genn/backends/cuda/backend.cc
  src/genn/backends/opencl/backend.cc
  src/genn/backends/single_threaded_cpu/backend.cc
  src/genn/genn/code_generator/backendSIMT.cc
  src/genn/genn/code_generator/generateRunner.cc
  src/genn/genn/code_generator/groupMerged.cc
  src/genn/genn/modelSpec.cc
  src/genn/genn/neuronGroup.cc
  tests/features/spike_event_recording/Makefile
  tests/features/spike_event_recording/model.cc
  tests/features/spike_event_recording/runner_guid.txt
  tests/features/spike_event_recording/spike_event_recording.sln
  tests/features/spike_event_recording/spike_event_recording.vcxproj
  tests/features/spike_event_recording/test.cc
  tests/features/spike_recording/Makefile
  tests/features/spike_recording/model.cc
  tests/features/spike_recording/runner_guid.txt
  tests/features/spike_recording/spike_recording.sln
  tests/features/spike_recording/spike_recording.vcxproj
  tests/features/spike_recording/test.cc
  userproject/PotjansMicrocircuit_project/model/PotjansMicrocircuit.cc
  userproject/PotjansMicrocircuit_project/model/PotjansMicrocircuitSim.cc
  userproject/include/sharedLibraryModel.h
  userproject/include/spikeRecorder.h
Labels: enhancement

#375 Correct calculation of neuronIDs in writeTextSpikeRecording
  userproject/include/spikeRecorder.h
Labels: bug
