Repository genn-team/genn, pull requests merged in 2021-11, with the labels that each got.

#472 Sync PyGeNN version to main GeNN version
  pygenn/__init__.py
  setup.py
Labels: enhancement, PyGeNN

#476 Include model name in DLL name on Windows
  generate_swig_interfaces.py
  include/genn/genn/code_generator/backendBase.h
  include/genn/genn/code_generator/generateMSBuild.h
  pygenn/genn_model.py
  src/genn/generator/generator.cc
  src/genn/genn/code_generator/generateMSBuild.cc
  src/spineml/generator/main.cc
  userproject/include/sharedLibraryModel.h
Labels: bug, windows

#479 Add to pre
  bin/genn-buildmodel.sh
  doxygen/10_UserManual.dox
  include/genn/genn/code_generator/groupMerged.h
  include/genn/genn/neuronGroup.h
  include/genn/genn/neuronGroupInternal.h
  include/genn/genn/synapseGroup.h
  include/genn/genn/synapseGroupInternal.h
  makedoc.sh
  pygenn/genn_groups.py
  src/genn/backends/single_threaded_cpu/backend.cc
  src/genn/genn/code_generator/backendSIMT.cc
  src/genn/genn/code_generator/generateRunner.cc
  src/genn/genn/code_generator/groupMerged.cc
  src/genn/genn/code_generator/initGroupMerged.cc
  src/genn/genn/code_generator/neuronUpdateGroupMerged.cc
  src/genn/genn/code_generator/presynapticUpdateStrategySIMT.cc
  src/genn/genn/neuronGroup.cc
  src/genn/genn/synapseGroup.cc
  tests/features/pre_output_decode_matrix_cont_individualg_dense/Makefile
  tests/features/pre_output_decode_matrix_cont_individualg_dense/model.cc
  tests/features/pre_output_decode_matrix_cont_individualg_dense/pre_output_decode_matrix_cont_individualg_dense.sln
  tests/features/pre_output_decode_matrix_cont_individualg_dense/pre_output_decode_matrix_cont_individualg_dense.vcxproj
  tests/features/pre_output_decode_matrix_cont_individualg_dense/runner_guid.txt
  tests/features/pre_output_decode_matrix_cont_individualg_dense/test.cc
  tests/features/pre_output_decode_matrix_event_individualg_dense/Makefile
  tests/features/pre_output_decode_matrix_event_individualg_dense/model.cc
  tests/features/pre_output_decode_matrix_event_individualg_dense/pre_output_decode_matrix_event_individualg_dense.sln
  tests/features/pre_output_decode_matrix_event_individualg_dense/pre_output_decode_matrix_event_individualg_dense.vcxproj
  tests/features/pre_output_decode_matrix_event_individualg_dense/runner_guid.txt
  tests/features/pre_output_decode_matrix_event_individualg_dense/test.cc
  tests/features/pre_output_decode_matrix_individualg_dense/Makefile
  tests/features/pre_output_decode_matrix_individualg_dense/model.cc
  tests/features/pre_output_decode_matrix_individualg_dense/pre_output_decode_matrix_individualg_dense.sln
  tests/features/pre_output_decode_matrix_individualg_dense/pre_output_decode_matrix_individualg_dense.vcxproj
  tests/features/pre_output_decode_matrix_individualg_dense/runner_guid.txt
  tests/features/pre_output_decode_matrix_individualg_dense/test.cc
  tests/features/pre_output_decode_matrix_post_learn_individualg_dense/Makefile
  tests/features/pre_output_decode_matrix_post_learn_individualg_dense/model.cc
  tests/features/pre_output_decode_matrix_post_learn_individualg_dense/pre_output_decode_matrix_post_learn_individualg_dense.sln
  tests/features/pre_output_decode_matrix_post_learn_individualg_dense/pre_output_decode_matrix_post_learn_individualg_dense.vcxproj
  tests/features/pre_output_decode_matrix_post_learn_individualg_dense/runner_guid.txt
  tests/features/pre_output_decode_matrix_post_learn_individualg_dense/test.cc
  tests/unit/neuronGroup.cc
  tests/utils/simulation_test_cont_decoder_matrix_inv.h
  tests/utils/simulation_test_decoder_matrix_inv.h
Labels: enhancement

#478 Proper implementation of kernel weights
  include/genn/backends/single_threaded_cpu/backend.h
  include/genn/genn/code_generator/backendBase.h
  include/genn/genn/code_generator/backendSIMT.h
  include/genn/genn/code_generator/codeGenUtils.h
  include/genn/genn/code_generator/groupMerged.h
  include/genn/genn/code_generator/initGroupMerged.h
  include/genn/genn/code_generator/modelSpecMerged.h
  include/genn/genn/synapseGroup.h
  include/genn/genn/synapseMatrixType.h
  pygenn/genn_groups.py
  src/genn/backends/cuda/backend.cc
  src/genn/backends/opencl/backend.cc
  src/genn/backends/single_threaded_cpu/backend.cc
  src/genn/genn/code_generator/backendBase.cc
  src/genn/genn/code_generator/backendSIMT.cc
  src/genn/genn/code_generator/generateRunner.cc
  src/genn/genn/code_generator/groupMerged.cc
  src/genn/genn/code_generator/initGroupMerged.cc
  src/genn/genn/code_generator/modelSpecMerged.cc
  src/genn/genn/code_generator/presynapticUpdateStrategySIMT.cc
  src/genn/genn/code_generator/synapseUpdateGroupMerged.cc
  src/genn/genn/synapseGroup.cc
  tests/features/batch_var_init/Makefile
  tests/features/batch_var_init/batch_var_init.sln
  tests/features/batch_var_init/batch_var_init.vcxproj
  tests/features/batch_var_init/model.cc
  tests/features/batch_var_init/runner_guid.txt
  tests/features/batch_var_init/skip_SingleThreadedCPU
  tests/features/batch_var_init/test.cc
  tests/features/decode_matrix_conn_gen_kernelg_procedural/Makefile
  tests/features/decode_matrix_conn_gen_kernelg_procedural/decode_matrix_conn_gen_kernelg_procedural.sln
  tests/features/decode_matrix_conn_gen_kernelg_procedural/decode_matrix_conn_gen_kernelg_procedural.vcxproj
  tests/features/decode_matrix_conn_gen_kernelg_procedural/model.cc
  tests/features/decode_matrix_conn_gen_kernelg_procedural/runner_guid.txt
  tests/features/decode_matrix_conn_gen_kernelg_procedural/skip_SingleThreadedCPU
  tests/features/decode_matrix_conn_gen_kernelg_procedural/test.cc
  tests/features/var_init/model.cc
  tests/features/var_init/test.cc
Labels: enhancement

#489 Fixed for strided convolutions
  include/genn/genn/initSparseConnectivitySnippet.h
  src/genn/genn/code_generator/initGroupMerged.cc
  src/genn/genn/code_generator/neuronUpdateGroupMerged.cc
  src/genn/genn/code_generator/synapseUpdateGroupMerged.cc
Labels: bug
