Repository genn-team/genn, pull requests merged in 2021-07, with the labels that each got.

#431 Var location hashing
  include/genn/genn/currentSource.h
  include/genn/genn/currentSourceInternal.h
  include/genn/genn/customUpdate.h
  include/genn/genn/customUpdateInternal.h
  include/genn/genn/neuronGroup.h
  include/genn/genn/neuronGroupInternal.h
  include/genn/genn/synapseGroup.h
  include/genn/genn/synapseGroupInternal.h
  src/genn/genn/code_generator/modelSpecMerged.cc
  src/genn/genn/currentSource.cc
  src/genn/genn/customUpdate.cc
  src/genn/genn/neuronGroup.cc
  src/genn/genn/synapseGroup.cc
  tests/unit/modelSpecMerged.cc
Labels: bug

#432 PyGeNN helpers for accessing model internals
  include/genn/genn/synapseGroup.h
  include/genn/genn/synapseGroupInternal.h
  pygenn/genn_groups.py
  pygenn/genn_model.py
Labels: PyGeNN, enhancement

#433 PyGeNN exception handling
  generate_swig_interfaces.py
  pygenn/genn_wrapper/swig/Models.i
  pygenn/genn_wrapper/swig/Snippet.i
Labels: PyGeNN, bug

#436 Include versions in hash
  src/genn/MakefileCommon
  src/genn/genn/Makefile
  src/genn/genn/code_generator/modelSpecMerged.cc
  src/genn/genn/genn.vcxproj
Labels: enhancement

#438 std::function wrapping
  generate_swig_interfaces.py
Labels: PyGeNN, bug

#440 Fix issue where newly calculated memory estimate was added to cached value if model was changed
  src/genn/genn/code_generator/generateAll.cc
Labels: bug

#439 Nasty bugs in custom update kernels
  src/genn/backends/cuda/backend.cc
  src/genn/backends/opencl/backend.cc
Labels: CUDA backend, OpenCL, bug

#443 Validate population and variable names
  include/genn/genn/currentSource.h
  include/genn/genn/currentSourceModels.h
  include/genn/genn/customUpdate.h
  include/genn/genn/customUpdateModels.h
  include/genn/genn/gennUtils.h
  include/genn/genn/initSparseConnectivitySnippet.h
  include/genn/genn/initVarSnippet.h
  include/genn/genn/models.h
  include/genn/genn/neuronGroup.h
  include/genn/genn/neuronModels.h
  include/genn/genn/postsynapticModels.h
  include/genn/genn/snippet.h
  include/genn/genn/weightUpdateModels.h
  src/genn/genn/customUpdateModels.cc
  src/genn/genn/gennUtils.cc
  src/genn/genn/initSparseConnectivitySnippet.cc
  src/genn/genn/models.cc
  src/genn/genn/neuronModels.cc
  src/genn/genn/synapseGroup.cc
  src/genn/genn/weightUpdateModels.cc
  tests/unit/currentSource.cc
  tests/unit/customUpdate.cc
  tests/unit/gennUtils.cc
  tests/unit/neuronGroup.cc
  tests/unit/synapseGroup.cc
  tests/unit/unit.vcxproj
Labels: enhancement

#445 Setting spikes manually from PyGeNN
  pygenn/genn_groups.py
Labels: PyGeNN, enhancement

#444 Use symbolic links in /tmp to fix "path name spaces problem"
  bin/genn-buildmodel.sh
Labels: bug, linux, mac
