Repository genn-team/genn, pull requests merged in 2022-10, with the labels that each got.

#547 Connectivity hashing bug
  src/genn/genn/code_generator/groupMerged.cc
  tests/unit/modelSpecMerged.cc
Labels: bug

#548 build: Dockerfile and docker-compose to launch notebook with pygenn resolves genn-team/genn#546
  .gitignore
  Makefile
  build_steps/.dockerignore
  build_steps/Dockerfile
  build_steps/docker-compose.yml
  build_steps/entrypoint.sh
  pygenn/README.md
  pygenn/notebooks/.gitkeep
Labels: hacktoberfest, hacktoberfest-accepted

#551 std::uniform_int_distribution operates on closed interval
  src/genn/generator/generator.vcxproj
  userproject/tools/gen_input_structured.cc
Labels: bug, userprojects

#540 Fixed potential bug where RNG isn't instantiated
  src/genn/backends/single_threaded_cpu/backend.cc
  src/genn/genn/code_generator/backendSIMT.cc
  tests/unit/customUpdate.cc
  tests/unit/neuronGroup.cc
Labels: bug

#550 Docker
  .dockerignore
  Dockerfile
  Makefile
  README.md
  bin/genn-docker-entrypoint.sh
Labels: enhancement
