Repository genn-team/genn, pull requests merged in 2024-04, with the labels that each got.

#617 Pydoc proofread
  docs/bibliography.rst
  docs/building_networks.rst
  docs/custom_models.rst
  docs/installation.rst
  docs/simulating_networks.rst
  docs/tutorials/mushroom_body/4_third_layer.ipynb
  docs/upgrading.rst
  include/genn/genn/modelSpec.h
  include/genn/genn/neuronModels.h
  include/genn/genn/synapseMatrixType.h
  include/genn/genn/varAccess.h
  include/genn/genn/varLocation.h
  pygenn/genn_model.py
  pygenn/src/docStrings.h
Labels: documentation

#618 Use warp shuffles for addToPre when using postsynaptic parallelism
  .dockerignore
  Dockerfile
  include/genn/backends/cuda/backend.h
  include/genn/genn/code_generator/backendSIMT.h
  src/genn/backends/cuda/backend.cc
  src/genn/genn/code_generator/backendBase.cc
  src/genn/genn/code_generator/backendSIMT.cc
  src/genn/genn/code_generator/presynapticUpdateStrategySIMT.cc
  tests/features/test_event_propagation.py
Labels: enhancement, CUDA backend

#621 Rebuild ``remap`` and ``colLength`` after custom connectivity updates
  include/genn/backends/cuda/backend.h
  include/genn/genn/code_generator/backendBase.h
  include/genn/genn/code_generator/backendSIMT.h
  include/genn/genn/code_generator/customConnectivityUpdateGroupMerged.h
  include/genn/genn/code_generator/modelSpecMerged.h
  include/genn/genn/customConnectivityUpdate.h
  include/genn/genn/customConnectivityUpdateInternal.h
  include/genn/genn/runtime/runtime.h
  pygenn/genn_model.py
  pygenn/src/runtime.cc
  src/genn/backends/cuda/backend.cc
  src/genn/backends/single_threaded_cpu/backend.cc
  src/genn/genn/code_generator/backendBase.cc
  src/genn/genn/code_generator/backendSIMT.cc
  src/genn/genn/code_generator/customConnectivityUpdateGroupMerged.cc
  src/genn/genn/code_generator/generateRunner.cc
  src/genn/genn/code_generator/modelSpecMerged.cc
  src/genn/genn/customConnectivityUpdate.cc
  src/genn/genn/runtime/runtime.cc
  tests/features/test_custom_connectivity_update.py
  tests/unit/customConnectivityUpdate.cc
Labels: bug
