Repository genn-team/genn, pull requests merged in 2025-05, with the labels that each got.

#676 Add pygenn wrappers for get_target_var() and set_target_var() on CurrentSource
  pygenn/src/genn.cc
Labels: bug, PyGeNN

#679 Fix pretty print bugs
  include/genn/genn/code_generator/environment.h
  src/genn/genn/code_generator/standardLibrary.cc
  src/genn/genn/transpiler/prettyPrinter.cc
  tests/unit/prettyPrinter.cc
  tests/unit/unit.vcxproj
Labels: bug

#685 Fixes RNG initialisation issues
  src/genn/genn/code_generator/modelSpecMerged.cc
Labels: bug, CUDA backend
