Repository genn-team/genn, pull requests merged in 2025-08, with the labels that each got.

#702 Fixed really nasty bug
  src/genn/genn/code_generator/presynapticUpdateStrategySIMT.cc
  src/genn/genn/transpiler/prettyPrinter.cc
  src/genn/genn/transpiler/typeChecker.cc
  tests/features/test_event_propagation.py
Labels: bug

#694 Fixed several issues working with sparse connectivity in PyGeNN
  pygenn/genn_groups.py
  pygenn/model_preprocessor.py
  pygenn/src/genn.cc
  tests/features/test_sparse.py
Labels: bug, PyGeNN

#707 setup.py: fix macOS dylib packaging and runtime linking
  setup.py
Labels: bug, PyGeNN, mac
